
CREATE TABLE ANSWERS
(
  ANSWERS_UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '답변대표값',
  USERS_UNIQUE_ID   VARCHAR(200) NOT NULL COMMENT '사용자대표값'
) COMMENT '답변';

CREATE TABLE ANSWERS_LIST
(
  ANSWERS_UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '답변대표값',
  ANSWERS           VARCHAR(200) NOT NULL COMMENT '답변',
  PRIMARY KEY (ANSWERS_UNIQUE_ID)
) COMMENT '답변 목록';

CREATE TABLE QUESTIONS
(
  USERS_UNIQUE_ID     VARCHAR(200) NOT NULL COMMENT '사용자대표값',
  QUESTIONS_UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '문항대표값'
) COMMENT '문항';

CREATE TABLE QUESTIONS_LIST
(
  QUESTIONS_UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '문항대표값',
  QUESTIONS           VARCHAR(200) NOT NULL COMMENT '문항',
  PRIMARY KEY (QUESTIONS_UNIQUE_ID)
) COMMENT '문항 목록';

CREATE TABLE USERS
(
  USERS_UNIQUE_ID VARCHAR(200) NOT NULL COMMENT '사용자대표값',
  USERS           VARCHAR(200) NOT NULL COMMENT '사용자',
  PHONE_NUMBER    VARCHAR(200) NOT NULL COMMENT '핸드폰번호',
  PRIMARY KEY (USERS_UNIQUE_ID)
) COMMENT '사용자(설문자)';

ALTER TABLE QUESTIONS
  ADD CONSTRAINT FK_QUESTIONS_LIST_TO_QUESTIONS
    FOREIGN KEY (QUESTIONS_UNIQUE_ID)
    REFERENCES QUESTIONS_LIST (QUESTIONS_UNIQUE_ID);

ALTER TABLE QUESTIONS
  ADD CONSTRAINT FK_USERS_TO_QUESTIONS
    FOREIGN KEY (USERS_UNIQUE_ID)
    REFERENCES USERS (USERS_UNIQUE_ID);

ALTER TABLE ANSWERS
  ADD CONSTRAINT FK_USERS_TO_ANSWERS
    FOREIGN KEY (USERS_UNIQUE_ID)
    REFERENCES USERS (USERS_UNIQUE_ID);

ALTER TABLE ANSWERS
  ADD CONSTRAINT FK_ANSWERS_LIST_TO_ANSWERS
    FOREIGN KEY (ANSWERS_UNIQUE_ID)
    REFERENCES ANSWERS_LIST (ANSWERS_UNIQUE_ID);
